feat: support pnpm

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -19,13 +19,45 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+              echo "manager=pnpm" >> $GITHUB_OUTPUT
+              echo "command=install" >> $GITHUB_OUTPUT
+              echo "runner=pnpm" >> $GITHUB_OUTPUT
+              exit 0
+          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+              echo "manager=yarn" >> $GITHUB_OUTPUT
+              echo "command=install" >> $GITHUB_OUTPUT
+              echo "runner=yarn" >> $GITHUB_OUTPUT
+              exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+              echo "manager=npm" >> $GITHUB_OUTPUT
+              echo "command=ci" >> $GITHUB_OUTPUT
+              echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+              exit 0
+          else
+              echo "Unable to determine package manager"
+              exit 1
+          fi
+
       - uses: actions/setup-node@v4
         with:
           node-version: "20"
-      - run: npm ci
-      - run: npm run build
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - uses: pnpm/action-setup@v2
+        if: ${{ steps.detect-package-manager.outputs.manager == 'pnpm' }}
+        with:
+          version: 8
+
+      - run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - run: ${{ steps.detect-package-manager.outputs.runner }} run build
         env:
           BASE_PATH: /bannatienet
+          
       - uses: actions/upload-pages-artifact@v3
         with:
           path: ./out
